In [ ]:
import numpy as np
import tensorflow as tf

In [ ]:
corpus_raw = 'Hello World . Hello hi . hello queen'
corpus_raw = corpus_raw.lower()

In [ ]:
words = []
for word in corpus_raw.split():
    if word != '.':
        words.append(word)
words = set(words)
word2int = {}
int2word = {}
vocab_size = len(words)
for i,word in enumerate(words):
    word2int[word] = i
    int2word[i] = word

In [ ]:
print(words)
print(word2int)

{'hello', 'world', 'queen', 'hi'}
{'hello': 0, 'world': 1, 'queen': 2, 'hi': 3}


In [ ]:
raw_sentences = corpus_raw.split('.')
sentences = []
for sentence in raw_sentences:
    sentences.append(sentence.split())

In [ ]:
data = []
WINDOW_SIZE = 2
for sentence in sentences:
    for word_index, word in enumerate(sentence):
        for nb_word in sentence[max(word_index - WINDOW_SIZE, 0) : min(word_index + WINDOW_SIZE, len(sentence)) + 1] :
            if nb_word != word:
                data.append([word, nb_word])

In [ ]:
data

[['hello', 'world'],
 ['world', 'hello'],
 ['hello', 'hi'],
 ['hi', 'hello'],
 ['hello', 'queen'],
 ['queen', 'hello']]

In [ ]:
def to_one_hot(data_point_index, vocab_size):
    temp = np.zeros(vocab_size)
    temp[data_point_index] = 1
    return temp
x_train = []
y_train = []
for data_word in data:
    x_train.append(to_one_hot(word2int[ data_word[0] ], vocab_size))
    y_train.append(to_one_hot(word2int[ data_word[1] ], vocab_size))
x_train = np.asarray(x_train)
y_train = np.asarray(y_train)
print(y_train)


[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [1. 0. 0. 0.]]


In [ ]:
import tensorflow as tf


In [ ]:
# Assuming you are using eager execution (TF 2.x default)
import tensorflow as tf

# Define input placeholders as regular Python variables
x = tf.compat.v1.placeholder(dtype=tf.float32, shape=(None, vocab_size), name='x')
y_label = tf.compat.v1.placeholder(dtype=tf.float32, shape=(None, vocab_size), name='y_label')


In [ ]:
import tensorflow as tf

EMBEDDING_DIM = 50  # Adjust this as needed
W1 = tf.Variable(tf.random.normal([vocab_size, EMBEDDING_DIM]))
b1 = tf.Variable(tf.random.normal([EMBEDDING_DIM]))
hidden_representation = tf.add(tf.matmul(x, W1), b1)


In [ ]:
import numpy as np

# Hypothetical vocabulary size and embedding dimension
vocab_size = 1000
embedding_dim = 100

# Example one-hot encoded training data
# Replace these with your actual one-hot encoded data
x_train = np.random.randint(2, size=(2, 5))  # Example input data
y_train = np.random.randint(2, size=(2, 5))  # Example target data

# Make sure x_train and y_train have the same number of samples (num_samples)


In [ ]:
print(x_train)


[[0 0 1 0 1]
 [1 1 0 0 0]]


In [ ]:
print(y_train)

[[1 1 1 1 0]
 [0 1 1 1 1]]


In [17]:
import torch
import torch.nn as nn
import torch.optim as optim

# Define your model using PyTorch
class WordEmbeddingModel(nn.Module):
    def __init__(self, vocab_size, embedding_dim):
        super(WordEmbeddingModel, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.fc = nn.Linear(embedding_dim, vocab_size)

    def forward(self, x):
        embedded = self.embedding(x)
        output = self.fc(embedded)
        return torch.nn.functional.softmax(output, dim=1)

# Define your model and loss function
vocab_size =5  # Define your vocabulary size
embedding_dim = 100  # Define the embedding dimension
model = WordEmbeddingModel(vocab_size, embedding_dim)
criterion = nn.CrossEntropyLoss()
optimizer = optim.SGD(model.parameters(), lr=0.1)

# Replace these placeholders with your actual training data
#x_train = torch.Tensor(your_x_train_data).long()
#y_train = torch.Tensor(your_y_train_data).long()
x_train = np.random.randint(2, size=(2, 5))  # Example input data
y_train = np.random.randint(2, size=(2, 5))
x_train = torch.Tensor([[0, 0, 1, 0, 1],
 [1 ,1 ,0 ,0 ,0]]).long()
y_train = torch.Tensor([[1 ,1, 1, 1, 0],
 [0 ,1 ,1 ,1 ,1]]).long()
# Training loop
n_iters = 10000
for i in range(n_iters):
    optimizer.zero_grad()
    outputs = model(x_train)
    loss = criterion(outputs, y_train)
    loss.backward()
    optimizer.step()
    print(loss.item())

Streaming output truncated to the last 5000 lines.
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085
1.5890268087387085